## Write a Numpy program to compute the multiplication of two given matrixes

In [9]:
import numpy as np





def mult(m1,m2):  
  c = m1 * m2 # element wise mult
  return c

In [10]:
m1=np.random.rand(9)
m2=np.random.rand(9)
m1 = m1.reshape(3,3)
m2 = m2.reshape(3,3)

mult(m1,m2)





array([[0.12513428, 0.19465331, 0.05409362],
       [0.0646493 , 0.03930762, 0.00143807],
       [0.07711709, 0.04013717, 0.16136607]])

## Write a NumPy program to compute the determinant of a given square array

In [13]:
def determinant(m):
  assert m.shape[0] == m.shape[1] , 'Not square mat'
  d=np.linalg.det(m)
  return d


In [16]:
m=np.array([[1,2],[3,4]])
determinant(m)

-2.0000000000000004

## Write a NumPy program to compute the cross product of two given vectors

In [22]:
def cross_prod(m1,m2):
  c = np.cross(m1,m2)
  return c


In [20]:
m1=np.array([[0,2],[4,5]])
m2=np.array([[1,3],[8,3]])
cross_prod(m1,m2)

array([ -2, -28])

## Write a NumPy program to compute the condition number of a given matrix

In [25]:

def func(arr):
  return np.linalg.cond(arr)

In [26]:
arr=np.array([[1,2,3],[0,9,2]])
func(arr)

3.7270027264915293

## Write a NumPy program to compute the inverse of a given matrix

In [36]:

def inverse(m):
  i = np.linalg.inv(m)
  return i

In [41]:
mat=np.array([[1,2]
              ,[3,4]])

m_inv=inverse(mat)
m_inv


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [42]:
mat.dot(m_inv) # = I

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])